### ISSUE TITLE
 import FinGAN

### ISSUE THREAD

**Issue by Med-Rokaimi** [milenavuletic/Fin-GAN#1]
First, thank you for this amazing repos.
Can you please explain more abour this import line:
`import FinGAN`
as there is no FinGAN file or class included here.
Thank you

**Comment by milenavuletic** [comment]
Hi Mohamed,

It is the FinGAN_online, I just gave an example of some previous code on my
computer with a slightly less cleaned version of FinGAN.py file :)

Best wishes,
Milena
